name: parkshield_mobile
description: ParkShield AI mobile client.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  app_links: ^7.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_map: ^8.3.1
  flutter_local_notifications: ^22.0.1
  geolocator: ^14.0.3
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.2.3
  intl: ^0.20.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
